version: '3'

services:
  rccghgemen:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
    env_file: .env
    volumes:
      - .:/app
